/**
 *
 * @type {{MISSING_TOKEN: string, INVALID_TOKEN_SCHEMA: string, INVALID_TOKEN: string, TOKEN_BLACKLISTED: string, UNKNOWN_ERROR: string}}
 */
module.exports = {
    UNKNOWN_ERROR: 'UNKNOWN_ERROR',
    MISSING_TOKEN: 'MISSING_TOKEN',
    INVALID_TOKEN_SCHEMA: 'INVALID_TOKEN_SCHEMA',
    INVALID_TOKEN: 'INVALID_TOKEN',
    CORRUPTED_TOKEN: 'CORRUPTED_TOKEN',
    TOKEN_BLACKLISTED: 'TOKEN_BLACKLISTED',

    // Json web token errors
    TOKEN_EXPIRED: 'TOKEN_EXPIRED',
    JWT_MALFORMED: 'JWT_MALFORMED',
    JWT_SIGNATURE_IS_REQUIRED: 'JWT_SIGNATURE_IS_REQUIRED',
    INVALID_SIGNATURE: 'INVALID_SIGNATURE',
    JWT_AUDIENCE_INVALID: 'JWT_AUDIENCE_INVALID',
    JWT_ISSUER_INVALID: 'JWT_ISSUER_INVALID',
    JWT_ID_INVALID: 'JWT_ID_INVALID',
    JWT_SUBJECT_INVALID: 'JWT_SUBJECT_INVALID',
};